// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterfacecontract

import "github.com/iotaledger/wasp/packages/vm/wasmlib"

const (
	ScName        = "alphainterfacecontract"
	ScDescription = "AlphaInterfaceContract description"
	HScName       = wasmlib.ScHname(0x584a6111)
)

const (
	ParamNumber   = wasmlib.Key("number")
	ParamOwner    = wasmlib.Key("owner")
	ParamReceiver = wasmlib.Key("receiver")
)

const ResultOwner = wasmlib.Key("owner")

const (
	StateOwner        = wasmlib.Key("owner")
	StateTransactions = wasmlib.Key("transactions")
)

const (
	FuncInit     = "init"
	FuncSetOwner = "setOwner"
	FuncTransfer = "transfer"
	ViewGetOwner = "getOwner"
)

const (
	HFuncInit     = wasmlib.ScHname(0x1f44d644)
	HFuncSetOwner = wasmlib.ScHname(0x2a15fe7b)
	HFuncTransfer = wasmlib.ScHname(0xa15da184)
	HViewGetOwner = wasmlib.ScHname(0x137107a6)
)
