// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterfacecontract

import "github.com/iotaledger/wasp/packages/vm/wasmlib"

const (
	IdxParamNumber       = 0
	IdxParamOwner        = 1
	IdxParamReceiver     = 2
	IdxResultOwner       = 3
	IdxStateOwner        = 4
	IdxStateTransactions = 5
)

const keyMapLen = 6

var keyMap = [keyMapLen]wasmlib.Key{
	ParamNumber,
	ParamOwner,
	ParamReceiver,
	ResultOwner,
	StateOwner,
	StateTransactions,
}

var idxMap [keyMapLen]wasmlib.Key32
