// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterfacecontract

import "github.com/iotaledger/wasp/packages/vm/wasmlib"

const (
	IdxParamNumber        = 0
	IdxParamOwner         = 1
	IdxParamReceiver      = 2
	IdxResultOwner        = 3
	IdxResultTransactions = 4
	IdxStateOwner         = 5
	IdxStateTransactions  = 6
)

const keyMapLen = 7

var keyMap = [keyMapLen]wasmlib.Key{
	ParamNumber,
	ParamOwner,
	ParamReceiver,
	ResultOwner,
	ResultTransactions,
	StateOwner,
	StateTransactions,
}

var idxMap [keyMapLen]wasmlib.Key32
