name: AlphaInterfaceContract
description: AlphaInterfaceContract description
structs: {}
typedefs: {}
state:
  owner: AgentID // current owner of this smart contract
funcs:
  init:
    params:
      owner: AgentID? // optional owner of this smart contract
  setOwner:
    access: owner // current owner of this smart contract
    params:
      owner: AgentID // new owner of this smart contract
views:
  getOwner:
    results:
      owner: AgentID // current owner of this smart contract
