// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterfacecontract

import "github.com/iotaledger/wasp/packages/vm/wasmlib"

type ImmutableAlphaInterfaceContractState struct {
	id int32
}

func (s ImmutableAlphaInterfaceContractState) Owner() wasmlib.ScImmutableAgentID {
	return wasmlib.NewScImmutableAgentID(s.id, idxMap[IdxStateOwner])
}

func (s ImmutableAlphaInterfaceContractState) Transactions() ArrayOfImmutableTransaction {
	arrID := wasmlib.GetObjectID(s.id, idxMap[IdxStateTransactions], wasmlib.TYPE_ARRAY|wasmlib.TYPE_BYTES)
	return ArrayOfImmutableTransaction{objID: arrID}
}

type MutableAlphaInterfaceContractState struct {
	id int32
}

func (s MutableAlphaInterfaceContractState) Owner() wasmlib.ScMutableAgentID {
	return wasmlib.NewScMutableAgentID(s.id, idxMap[IdxStateOwner])
}

func (s MutableAlphaInterfaceContractState) Transactions() ArrayOfMutableTransaction {
	arrID := wasmlib.GetObjectID(s.id, idxMap[IdxStateTransactions], wasmlib.TYPE_ARRAY|wasmlib.TYPE_BYTES)
	return ArrayOfMutableTransaction{objID: arrID}
}
