// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterface2

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "alphainterface2"
	ScDescription = "alphainterface2 description"
	HScName       = wasmlib.ScHname(0x426940a3)
)

const (
	ParamAmount   = wasmlib.Key("amount")
	ParamCountry  = wasmlib.Key("country")
	ParamCropIdx  = wasmlib.Key("cropIdx")
	ParamName     = wasmlib.Key("name")
	ParamOrderIdx = wasmlib.Key("orderIdx")
	ParamOwner    = wasmlib.Key("owner")
	ParamPrice    = wasmlib.Key("price")
	ParamType     = wasmlib.Key("type")
)

const (
	ResultCrops   = wasmlib.Key("crops")
	ResultOrders  = wasmlib.Key("orders")
	ResultOwner   = wasmlib.Key("owner")
	ResultWallets = wasmlib.Key("wallets")
)

const (
	StateCrops   = wasmlib.Key("crops")
	StateOrders  = wasmlib.Key("orders")
	StateOwner   = wasmlib.Key("owner")
	StateWallets = wasmlib.Key("wallets")
)

const (
	FuncCloseOrder       = "closeOrder"
	FuncCreateOrder      = "createOrder"
	FuncInit             = "init"
	FuncSetCrop          = "setCrop"
	FuncSetOwner         = "setOwner"
	FuncViewGetMyWallets = "viewGetMyWallets"
	FuncViewGetOrders    = "viewGetOrders"
	ViewGetCrops         = "getCrops"
	ViewGetOrders        = "getOrders"
	ViewGetOwner         = "getOwner"
	ViewGetWallets       = "getWallets"
)

const (
	HFuncCloseOrder       = wasmlib.ScHname(0xfc422a52)
	HFuncCreateOrder      = wasmlib.ScHname(0xe3c7ac26)
	HFuncInit             = wasmlib.ScHname(0x1f44d644)
	HFuncSetCrop          = wasmlib.ScHname(0x321b14e9)
	HFuncSetOwner         = wasmlib.ScHname(0x2a15fe7b)
	HFuncViewGetMyWallets = wasmlib.ScHname(0x03614145)
	HFuncViewGetOrders    = wasmlib.ScHname(0x91a574be)
	HViewGetCrops         = wasmlib.ScHname(0x0f16dbb7)
	HViewGetOrders        = wasmlib.ScHname(0x53738744)
	HViewGetOwner         = wasmlib.ScHname(0x137107a6)
	HViewGetWallets       = wasmlib.ScHname(0xbd77d8e8)
)
