// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterface2

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAmount        = 0
	IdxParamCountry       = 1
	IdxParamCropIdx       = 2
	IdxParamName          = 3
	IdxParamOrderIdx      = 4
	IdxParamOwner         = 5
	IdxParamPrice         = 6
	IdxParamType          = 7
	IdxResultCrop         = 8
	IdxResultCrops        = 9
	IdxResultCropsString  = 10
	IdxResultOrders       = 11
	IdxResultOrdersString = 12
	IdxResultOwner        = 13
	IdxResultWallets      = 14
	IdxStateCrops         = 15
	IdxStateOrders        = 16
	IdxStateOwner         = 17
	IdxStateWallets       = 18
)

const keyMapLen = 19

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAmount,
	ParamCountry,
	ParamCropIdx,
	ParamName,
	ParamOrderIdx,
	ParamOwner,
	ParamPrice,
	ParamType,
	ResultCrop,
	ResultCrops,
	ResultCropsString,
	ResultOrders,
	ResultOrdersString,
	ResultOwner,
	ResultWallets,
	StateCrops,
	StateOrders,
	StateOwner,
	StateWallets,
}

var idxMap [keyMapLen]wasmlib.Key32
