// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterface2

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAmount    = 0
	IdxParamCountry   = 1
	IdxParamCropIdx   = 2
	IdxParamName      = 3
	IdxParamOrderIdx  = 4
	IdxParamOwner     = 5
	IdxParamPrice     = 6
	IdxParamType      = 7
	IdxParamWalletIdx = 8
	IdxResultCrops    = 9
	IdxResultOrders   = 10
	IdxResultOwner    = 11
	IdxResultWallets  = 12
	IdxStateCrops     = 13
	IdxStateOrders    = 14
	IdxStateOwner     = 15
	IdxStateWallets   = 16
)

const keyMapLen = 17

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAmount,
	ParamCountry,
	ParamCropIdx,
	ParamName,
	ParamOrderIdx,
	ParamOwner,
	ParamPrice,
	ParamType,
	ParamWalletIdx,
	ResultCrops,
	ResultOrders,
	ResultOwner,
	ResultWallets,
	StateCrops,
	StateOrders,
	StateOwner,
	StateWallets,
}

var idxMap [keyMapLen]wasmlib.Key32
