// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterface2

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAmount   = 0
	IdxParamCountry  = 1
	IdxParamCropIdx  = 2
	IdxParamName     = 3
	IdxParamOrderIdx = 4
	IdxParamOwner    = 5
	IdxParamPrice    = 6
	IdxParamType     = 7
	IdxResultCrops   = 8
	IdxResultOrders  = 9
	IdxResultOwner   = 10
	IdxResultWallets = 11
	IdxStateCrops    = 12
	IdxStateOrders   = 13
	IdxStateOwner    = 14
	IdxStateWallets  = 15
)

const keyMapLen = 16

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAmount,
	ParamCountry,
	ParamCropIdx,
	ParamName,
	ParamOrderIdx,
	ParamOwner,
	ParamPrice,
	ParamType,
	ResultCrops,
	ResultOrders,
	ResultOwner,
	ResultWallets,
	StateCrops,
	StateOrders,
	StateOwner,
	StateWallets,
}

var idxMap [keyMapLen]wasmlib.Key32
