// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

//nolint:dupl
package alphainterface2

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

func OnLoad() {
	exports := wasmlib.NewScExports()
	exports.AddFunc(FuncCloseOrder, funcCloseOrderThunk)
	exports.AddFunc(FuncCreateOrder, funcCreateOrderThunk)
	exports.AddFunc(FuncInit, funcInitThunk)
	exports.AddFunc(FuncSetCrop, funcSetCropThunk)
	exports.AddFunc(FuncSetOwner, funcSetOwnerThunk)
	exports.AddFunc(FuncViewGetMyWallets, funcViewGetMyWalletsThunk)
	exports.AddFunc(FuncViewGetOrders, funcViewGetOrdersThunk)
	exports.AddView(ViewGetCrops, viewGetCropsThunk)
	exports.AddView(ViewGetOrders, viewGetOrdersThunk)
	exports.AddView(ViewGetOwner, viewGetOwnerThunk)
	exports.AddView(ViewGetWallets, viewGetWalletsThunk)

	for i, key := range keyMap {
		idxMap[i] = key.KeyID()
	}
}

type CloseOrderContext struct {
	Params ImmutableCloseOrderParams
	State  Mutablealphainterface2State
}

func funcCloseOrderThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("alphainterface2.funcCloseOrder")
	f := &CloseOrderContext{
		Params: ImmutableCloseOrderParams{
			id: wasmlib.OBJ_ID_PARAMS,
		},
		State: Mutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	ctx.Require(f.Params.OrderIdx().Exists(), "missing mandatory orderIdx")
	funcCloseOrder(ctx, f)
	ctx.Log("alphainterface2.funcCloseOrder ok")
}

type CreateOrderContext struct {
	Params ImmutableCreateOrderParams
	State  Mutablealphainterface2State
}

func funcCreateOrderThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("alphainterface2.funcCreateOrder")
	f := &CreateOrderContext{
		Params: ImmutableCreateOrderParams{
			id: wasmlib.OBJ_ID_PARAMS,
		},
		State: Mutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	ctx.Require(f.Params.Amount().Exists(), "missing mandatory amount")
	ctx.Require(f.Params.CropIdx().Exists(), "missing mandatory cropIdx")
	ctx.Require(f.Params.Price().Exists(), "missing mandatory price")
	ctx.Require(f.Params.Type().Exists(), "missing mandatory type")
	funcCreateOrder(ctx, f)
	ctx.Log("alphainterface2.funcCreateOrder ok")
}

type InitContext struct {
	Params ImmutableInitParams
	State  Mutablealphainterface2State
}

func funcInitThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("alphainterface2.funcInit")
	f := &InitContext{
		Params: ImmutableInitParams{
			id: wasmlib.OBJ_ID_PARAMS,
		},
		State: Mutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	funcInit(ctx, f)
	ctx.Log("alphainterface2.funcInit ok")
}

type SetCropContext struct {
	Params ImmutableSetCropParams
	State  Mutablealphainterface2State
}

func funcSetCropThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("alphainterface2.funcSetCrop")
	// current owner of this smart contract
	access := ctx.State().GetAgentID(wasmlib.Key("owner"))
	ctx.Require(access.Exists(), "access not set: owner")
	ctx.Require(ctx.Caller() == access.Value(), "no permission")

	f := &SetCropContext{
		Params: ImmutableSetCropParams{
			id: wasmlib.OBJ_ID_PARAMS,
		},
		State: Mutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	ctx.Require(f.Params.Country().Exists(), "missing mandatory country")
	ctx.Require(f.Params.Name().Exists(), "missing mandatory name")
	funcSetCrop(ctx, f)
	ctx.Log("alphainterface2.funcSetCrop ok")
}

type SetOwnerContext struct {
	Params ImmutableSetOwnerParams
	State  Mutablealphainterface2State
}

func funcSetOwnerThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("alphainterface2.funcSetOwner")
	// current owner of this smart contract
	access := ctx.State().GetAgentID(wasmlib.Key("owner"))
	ctx.Require(access.Exists(), "access not set: owner")
	ctx.Require(ctx.Caller() == access.Value(), "no permission")

	f := &SetOwnerContext{
		Params: ImmutableSetOwnerParams{
			id: wasmlib.OBJ_ID_PARAMS,
		},
		State: Mutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	ctx.Require(f.Params.Owner().Exists(), "missing mandatory owner")
	funcSetOwner(ctx, f)
	ctx.Log("alphainterface2.funcSetOwner ok")
}

type ViewGetMyWalletsContext struct {
	Results MutableViewGetMyWalletsResults
	State   Mutablealphainterface2State
}

func funcViewGetMyWalletsThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("alphainterface2.funcViewGetMyWallets")
	f := &ViewGetMyWalletsContext{
		Results: MutableViewGetMyWalletsResults{
			id: wasmlib.OBJ_ID_RESULTS,
		},
		State: Mutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	funcViewGetMyWallets(ctx, f)
	ctx.Log("alphainterface2.funcViewGetMyWallets ok")
}

type ViewGetOrdersContext struct {
	Results MutableViewGetOrdersResults
	State   Mutablealphainterface2State
}

func funcViewGetOrdersThunk(ctx wasmlib.ScFuncContext) {
	ctx.Log("alphainterface2.funcViewGetOrders")
	f := &ViewGetOrdersContext{
		Results: MutableViewGetOrdersResults{
			id: wasmlib.OBJ_ID_RESULTS,
		},
		State: Mutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	funcViewGetOrders(ctx, f)
	ctx.Log("alphainterface2.funcViewGetOrders ok")
}

type GetCropsContext struct {
	Results MutableGetCropsResults
	State   Immutablealphainterface2State
}

func viewGetCropsThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("alphainterface2.viewGetCrops")
	f := &GetCropsContext{
		Results: MutableGetCropsResults{
			id: wasmlib.OBJ_ID_RESULTS,
		},
		State: Immutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	viewGetCrops(ctx, f)
	ctx.Log("alphainterface2.viewGetCrops ok")
}

type GetOrdersContext struct {
	Results MutableGetOrdersResults
	State   Immutablealphainterface2State
}

func viewGetOrdersThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("alphainterface2.viewGetOrders")
	f := &GetOrdersContext{
		Results: MutableGetOrdersResults{
			id: wasmlib.OBJ_ID_RESULTS,
		},
		State: Immutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	viewGetOrders(ctx, f)
	ctx.Log("alphainterface2.viewGetOrders ok")
}

type GetOwnerContext struct {
	Results MutableGetOwnerResults
	State   Immutablealphainterface2State
}

func viewGetOwnerThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("alphainterface2.viewGetOwner")
	f := &GetOwnerContext{
		Results: MutableGetOwnerResults{
			id: wasmlib.OBJ_ID_RESULTS,
		},
		State: Immutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	viewGetOwner(ctx, f)
	ctx.Log("alphainterface2.viewGetOwner ok")
}

type GetWalletsContext struct {
	Results MutableGetWalletsResults
	State   Immutablealphainterface2State
}

func viewGetWalletsThunk(ctx wasmlib.ScViewContext) {
	ctx.Log("alphainterface2.viewGetWallets")
	f := &GetWalletsContext{
		Results: MutableGetWalletsResults{
			id: wasmlib.OBJ_ID_RESULTS,
		},
		State: Immutablealphainterface2State{
			id: wasmlib.OBJ_ID_STATE,
		},
	}
	viewGetWallets(ctx, f)
	ctx.Log("alphainterface2.viewGetWallets ok")
}
