name: alphainterface2
description: alphainterface2 description
structs:
  Crop:
    idx: Int32 // crop index
    name: String // name of the crop
    country: String // the country name
  Order:
    idx: Int32 // order index
    cropIdx: Int32 // crop index
    walletIdx: Int32 // wallet index
    type: String // order type (sell, buy)
    amount: Int64 // limit amount left of the order
    price: Int64 // limit price of the order
    iota: Int64 // for buy order we need to specific iota incoming for reason when buy higher price than the market
    owner: AgentID // agent id of the owner
    status: String // order status (opening, matched, canceled)
  Wallet:
    idx: Int32 // wallet index
    owner: AgentID // agent id of the owner
    cropIdx: Int32 // crop index
    amount: Int64 // amount of crop
typedefs: {}
state:
  owner: AgentID // current owner of this smart contract
  crops: Crop[] // crop array
  orders: Order[] // order array
  wallets: Wallet[] // position array
funcs:
  init:
    params:
      owner: AgentID? // optional owner of this smart contract
  setOwner:
    access: owner // current owner of this smart contract
    params:
      owner: AgentID // new owner of this smart contract
  setCrop:
    access: owner // current owner of this smart contract
    params:
      name: String // name of the crop
      country: String // the country name
  createOrder:
    params:
      cropIdx: Int32 // crop index
      type: String // sell, buy
      price: Int64 // price
      amount: Int64 // amount
  closeOrder:
    params:
      orderIdx: Int32 // order index
  viewGetMyWallets:
    results:
      wallets: Wallet[]
  viewGetOrders:
    results:
      orders: Order[]
  setWalletAmount:
    access: owner // current owner of this smart contract
    params:
      walletIdx: Int32 // wallet id
      amount: Int64 // amount to set
views:
  getWallets:
    results:
      wallets: Wallet[]
  getOwner:
    results:
      owner: AgentID // current owner of this smart contract
  getOrders:
    results:
      orders: Order[]
  getCrops:
    results:
      crops: Crop[]
