// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterfacecontract

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamCountry          = 0
	IdxParamCropIdx          = 1
	IdxParamName             = 2
	IdxParamOrderIdx         = 3
	IdxParamOwner            = 4
	IdxParamPositionIdx      = 5
	IdxParamType             = 6
	IdxParamYield            = 7
	IdxResultCrop            = 8
	IdxResultCrops           = 9
	IdxResultCropsString     = 10
	IdxResultOrders          = 11
	IdxResultOrdersString    = 12
	IdxResultOwner           = 13
	IdxResultPositions       = 14
	IdxResultPositionsString = 15
	IdxStateCrops            = 16
	IdxStateOrders           = 17
	IdxStateOwner            = 18
	IdxStatePositions        = 19
)

const keyMapLen = 20

var keyMap = [keyMapLen]wasmlib.Key{
	ParamCountry,
	ParamCropIdx,
	ParamName,
	ParamOrderIdx,
	ParamOwner,
	ParamPositionIdx,
	ParamType,
	ParamYield,
	ResultCrop,
	ResultCrops,
	ResultCropsString,
	ResultOrders,
	ResultOrdersString,
	ResultOwner,
	ResultPositions,
	ResultPositionsString,
	StateCrops,
	StateOrders,
	StateOwner,
	StatePositions,
}

var idxMap [keyMapLen]wasmlib.Key32
