// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterfacecontract

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAmount      = 0
	IdxParamCountry     = 1
	IdxParamCropIdx     = 2
	IdxParamName        = 3
	IdxParamOrderIdx    = 4
	IdxParamOwner       = 5
	IdxParamPositionIdx = 6
	IdxParamType        = 7
	IdxParamYield       = 8
	IdxResultCrop       = 9
	IdxResultCrops      = 10
	IdxResultOrders     = 11
	IdxResultOwner      = 12
	IdxResultPositions  = 13
	IdxStateCrops       = 14
	IdxStateOrders      = 15
	IdxStateOwner       = 16
	IdxStatePositions   = 17
)

const keyMapLen = 18

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAmount,
	ParamCountry,
	ParamCropIdx,
	ParamName,
	ParamOrderIdx,
	ParamOwner,
	ParamPositionIdx,
	ParamType,
	ParamYield,
	ResultCrop,
	ResultCrops,
	ResultOrders,
	ResultOwner,
	ResultPositions,
	StateCrops,
	StateOrders,
	StateOwner,
	StatePositions,
}

var idxMap [keyMapLen]wasmlib.Key32
