// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package alphainterfacecontract

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamCountry     = 0
	IdxParamCropIdx     = 1
	IdxParamName        = 2
	IdxParamOrderIdx    = 3
	IdxParamOwner       = 4
	IdxParamPositionIdx = 5
	IdxParamType        = 6
	IdxParamYield       = 7
	IdxResultCrop       = 8
	IdxResultCrops      = 9
	IdxResultOrders     = 10
	IdxResultOwner      = 11
	IdxResultPositions  = 12
	IdxStateCrops       = 13
	IdxStateOrders      = 14
	IdxStateOwner       = 15
	IdxStatePositions   = 16
)

const keyMapLen = 17

var keyMap = [keyMapLen]wasmlib.Key{
	ParamCountry,
	ParamCropIdx,
	ParamName,
	ParamOrderIdx,
	ParamOwner,
	ParamPositionIdx,
	ParamType,
	ParamYield,
	ResultCrop,
	ResultCrops,
	ResultOrders,
	ResultOwner,
	ResultPositions,
	StateCrops,
	StateOrders,
	StateOwner,
	StatePositions,
}

var idxMap [keyMapLen]wasmlib.Key32
